#!/usr/bin/env python
"""
Bundle every cross-study table into one shareable workbook.

Run report.py first; this collects what it wrote plus the per-study score tables
into final_evaluations/results_v2/cross_study/all_results.xlsx.
"""

import pathlib
import sys

import pandas as pd

REPO = pathlib.Path(__file__).resolve().parent
RESULTS = REPO / "final_evaluations" / "results_v2"
CROSS = RESULTS / "cross_study"
OUT = CROSS / "all_results.xlsx"

README = pd.DataFrame([
    ("ABOUT", "Security and inclusivity in LLM-generated code — two user stories"),
    ("", ""),
    ("STORY 1", "Password recovery for a health portal. Cognitive condition: ADHD."),
    ("STORY 2", "MFA enrolment for online banking. Cognitive condition: dyslexia."),
    ("", "Each: 3 cases x 10 independent runs, generated by openai/gpt-5.6-terra."),
    ("", "Judged by 7 models, 2 tracks, 3 repeats each."),
    ("", ""),
    ("UNIT OF ANALYSIS", "artifact score = median across judges of (mean across 3 repeats)"),
    ("", "n = 10 per case; fewer where an artifact could not be scored."),
    ("", ""),
    ("COMPARABILITY", "Security constructs are identical across studies and comparable."),
    ("", "Inclusivity constructs are NOT: the studies target different cognitive"),
    ("", "conditions and name different dimensions. Compare overall scores only."),
    ("", ""),
    ("EXCLUSIONS", "mistralai/mistral-medium-3-5 dropped from story 1 SECURITY:"),
    ("", "  fixed response pattern, artifact-level SD 0.008."),
    ("", "openai/gpt-5.6-sol is the generator's own lab and is analysed separately."),
    ("", ""),
    ("TWO REPORT VARIANTS", "report_all.txt        every artifact as judged"),
    ("", "report_working_only.txt  known-dead client scripts removed"),
    ("", "Story 1 predates the client-script check and is unfiltered in both."),
    ("", ""),
    ("HEADLINE", "Story 1 inclusivity: p=0.0001, Cliff d=-1.00 (complete separation)"),
    ("", "Story 2 inclusivity: p=0.177 over all artifacts, p=0.0031 d=-0.97 over"),
    ("", "  working ones. Case 3 also produced 6/10 working vs 10/10 (chi2 p=0.0099)."),
    ("", "Security: not significant in either study."),
], columns=["", " "])

sheets = {"README": README}
for csv in sorted(CROSS.glob("*.csv")):
    sheets[csv.stem[:31]] = csv
for study, tag in (("password_recovery_health", "s1"), ("mfa_enrolment_banking", "s2")):
    sheets[f"{tag}_judgements"] = RESULTS / study / "scores_artifact.csv"
    sheets[f"{tag}_artifact_scores"] = RESULTS / study / "analysis" / "artifact_scores.csv"

with pd.ExcelWriter(OUT, engine="openpyxl") as xl:
    for name, src in sheets.items():
        df = src if isinstance(src, pd.DataFrame) else pd.read_csv(src)
        df.to_excel(xl, sheet_name=name[:31], index=False)
        ws = xl.sheets[name[:31]]
        for i, col in enumerate(df.columns, start=1):
            width = max([len(str(col))] + [len(str(v)) for v in df[col].head(60)]) + 2
            ws.column_dimensions[ws.cell(row=1, column=i).column_letter].width = min(width, 60)
        ws.freeze_panes = "A2"

print(f"wrote {OUT.relative_to(REPO)}  ({OUT.stat().st_size // 1024} KB, {len(sheets)} sheets)")
for n in sheets:
    print("  ", n)
