
/**
 * MFA Enrolment System — single-file Bun HTTPS server and mobile web SPA.
 * Run: bun app.ts
 * Security §§1–5: owner-bound sessions, CSRF, TLS cookies, headers, validation,
 * encrypted TOTP seed, hashed recovery codes, expiry and failed-attempt lockout.
 */
const enc = new TextEncoder(), dec = new TextDecoder();
const TRUSTED = "https://localhost:3000", ACADEMIC = Bun.env.MFA_REAL_PRODUCTION !== "true";
const IDLE = 20 * 60e3, ABS = 8 * 60 * 60e3, LOCK = 15 * 60e3, LIFE = 10 * 60e3, MAX = 5;
const TEST_SECRET = "JBSWY3DPEHPK3PXPX", TEST_ID = "123456";
const TEST_CODES = ["DEMO0001-CODE0001","DEMO0002-CODE0002","DEMO0003-CODE0003","DEMO0004-CODE0004","DEMO0005-CODE0005","DEMO0006-CODE0006","DEMO0007-CODE0007","DEMO0008-CODE0008"];
const key = await crypto.subtle.importKey("raw", crypto.getRandomValues(new Uint8Array(32)), { name: "AES-GCM" }, false, ["encrypt","decrypt"]);

type Stage = "identity"|"setup"|"confirm"|"recovery"|"complete";
type Session = { id:string; csrf:string; stage:Stage; created:number; seen:number };
type Guard = { failures:number; locked:number };
type Code = Guard & { hash:string; expires:number; used:boolean; next:number };
const sessions = new Map<string,Session>();
const account = {
  email:"marcus@example.com", password:"BankPass!42", identity:null as Code|null,
  secret:"", backups:[] as string[], enabled:false,
  totp:{failures:0,locked:0,used:new Set<number>()}, recovery:{failures:0,locked:0}, signin:{failures:0,locked:0}
};

const now=()=>Date.now(), random=(n:number)=>crypto.getRandomValues(new Uint8Array(n));
const token=(n=32)=>Buffer.from(random(n)).toString("base64url");
const sha=async(s:string)=>Buffer.from(await crypto.subtle.digest("SHA-256",enc.encode(s))).toString("base64url");
const encrypt=async(s:string)=>{const iv=random(12), c=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(s));return Buffer.from(iv).toString("base64url")+"."+Buffer.from(c).toString("base64url")};
const decrypt=async(s:string)=>{const [iv,c]=s.split(".");return dec.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:Buffer.from(iv,"base64url")},key,Buffer.from(c,"base64url")))};
function b32(a:Uint8Array){const A="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let o="",b=0,n=0;for(const x of a){b=b<<8|x;n+=8;while(n>=5){o+=A[b>>>(n-=5)&31]}}return o+(n?A[b<<(5-n)&31]:"")}
function unb32(s:string){const A="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let b=0,n=0,o:number[]=[];for(const c of s.replace(/[=\s]/g,"").toUpperCase()){const v=A.indexOf(c);if(v<0)throw Error();b=b<<5|v;n+=5;if(n>=8)o.push(b>>>(n-=8)&255)}return new Uint8Array(o)}
async function totp(secret:string,counter:number){const k=await crypto.subtle.importKey("raw",unb32(secret),{name:"HMAC",hash:"SHA-1"},false,["sign"]), d=new Uint8Array(8);let x=BigInt(counter);for(let i=7;i>=0;i--){d[i]=Number(x&255n);x>>=8n}const h=new Uint8Array(await crypto.subtle.sign("HMAC",k,d)),p=h[19]&15,v=((h[p]&127)<<24)|(h[p+1]<<16)|(h[p+2]<<8)|h[p+3];return String(v%1e6).padStart(6,"0")}
function cookies(r:Request){const o:Record<string,string>={};for(const x of (r.headers.get("cookie")||"").split(";")){const i=x.indexOf("=");if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())}return o}
const headers={"Cache-Control":"no-store","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Content-Security-Policy":"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'","Referrer-Policy":"no-referrer"};
function out(x:any,status=200,c:string[]=[]){const h=new Headers({...headers,"Content-Type":"application/json; charset=utf-8"});c.forEach(v=>h.append("Set-Cookie",v));return new Response(JSON.stringify(x),{status,headers:h})}
function session(r:Request){const s=sessions.get(cookies(r).mfa_session||""),t=now();if(!s||t-s.seen>IDLE||t-s.created>ABS)return null;s.seen=t;return s}
function protect(r:Request){const s=session(r);if(!s)return [null,out({ok:false,message:"Please sign in again to continue."},401)] as const;if(r.headers.get("origin")!==null&&r.headers.get("origin")!==TRUSTED)return [null,out({ok:false,message:"This request is not allowed."},403)] as const;if(r.headers.get("x-csrf-token")!==s.csrf)return [null,out({ok:false,message:"Please try that step again."},403)] as const;return [s,null] as const}
async function body(r:Request){try{return await r.json()}catch{return null}}
const otp=(x:any)=>typeof x==="string"&&/^\d{6}$/.test(x);
function stage(s:Session,a:Stage[]){return a.includes(s.stage)}
async function api(r:Request,p:string):Promise<Response>{
  if(p==="/api/signin"&&r.method==="POST"){const b=await body(r),c=cookies(r).mfa_csrf;if(!b||!c||c!==r.headers.get("x-csrf-token")||b.email!==account.email||b.password!==account.password)return out({ok:false,message:"Check your email and password, then try again."},401);const id=token(),csrf=token(24),s={id,csrf,stage:(account.enabled?"complete":"identity") as Stage,created:now(),seen:now()};sessions.set(id,s);return out({ok:true,csrf,stage:s.stage,academicMode:ACADEMIC,message:"Signed in."},200,[`mfa_session=${id}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`,`mfa_csrf=${csrf}; Path=/; Secure; SameSite=Strict; Max-Age=28800`])}
  if(p==="/api/me"){const s=session(r);return s?out({ok:true,csrf:s.csrf,stage:s.stage,academicMode:ACADEMIC}):out({ok:false},401)}
  const [s,fail]=protect(r);if(fail)return fail;
  if(p==="/api/identity/send"&&stage(s!,["identity"])){const code=ACADEMIC?TEST_ID:String(Math.floor(Math.random()*1e6)).padStart(6,"0");account.identity={hash:await sha(code),expires:now()+LIFE,used:false,failures:0,locked:0,next:now()+6e4};return out({ok:true,simulationCode:ACADEMIC?code:undefined,message:"A code was sent. In academic mode, it is in the browser console."})}
  if(p==="/api/identity/verify"&&stage(s!,["identity"])){const b=await body(r),x=account.identity;if(!otp(b?.code)||!x||x.used||x.expires<now()||await sha(b.code)!==x.hash)return out({ok:false,message:"That code did not match. Check all 6 digits or request another code."},400);x.used=true;s!.stage="setup";return out({ok:true,message:"Identity checked. Next, set up your authenticator."})}
  if(p==="/api/authenticator/setup"&&stage(s!,["setup"])){if(!account.secret)account.secret=await encrypt(ACADEMIC?TEST_SECRET:b32(random(20)));const secret=await decrypt(account.secret),uri=`otpauth://totp/Local%20Bank:marcus%40example.com?secret=${secret}&issuer=Local%20Bank&algorithm=SHA1&digits=6&period=30`;return out({ok:true,secret,uri})}
  if(p==="/api/authenticator/confirm"&&stage(s!,["setup","confirm"])){if(!account.secret)return out({ok:false,message:"Create a setup key first."},400);s!.stage="confirm";const code=ACADEMIC?await totp(await decrypt(account.secret),Math.floor(now()/30000)):undefined;return out({ok:true,simulationCode:code,message:"Now enter the current code from your authenticator."})}
  /* Task: CSRF-protected retry endpoint; no penalty and newly current simulated TOTP. */
  if(p==="/api/authenticator/refresh"&&stage(s!,["confirm"])){const code=ACADEMIC?await totp(await decrypt(account.secret),Math.floor(now()/30000)):undefined;return out({ok:true,simulationCode:code,message:"A new current test code is ready. Retrying is safe and does not count against you."})}
  if(p==="/api/authenticator/verify"&&stage(s!,["confirm"])){const b=await body(r),state=account.totp;if(state.locked>now())return out({ok:false,message:"Too many tries. Please wait, then try a new code."},429);let good=false,center=Math.floor(now()/30000),secret=await decrypt(account.secret);if(otp(b?.code))for(const n of [center-1,center,center+1])if(b.code===await totp(secret,n)&&!state.used.has(n)){good=true;state.used.add(n)}if(!good){if(++state.failures>=MAX)state.locked=now()+LOCK;return out({ok:false,message:"That code did not match or was already used. Get a new current code and try again."},400)}s!.stage="recovery";return out({ok:true,message:"Authenticator confirmed. Next, save your recovery codes."})}
  if(p==="/api/recovery/create"&&stage(s!,["recovery"])){const codes=ACADEMIC?[...TEST_CODES]:Array.from({length:8},()=>token(8).toUpperCase());account.backups=await Promise.all(codes.map(sha));return out({ok:true,codes,message:"Your recovery codes are ready. Save them somewhere private."})}
  if(p==="/api/recovery/finish"&&stage(s!,["recovery"])&&account.backups.length===8){account.enabled=true;s!.stage="complete";return out({ok:true,message:"MFA is now on."})}
  if(p==="/api/logout"){sessions.delete(s!.id);return out({ok:true},200,["mfa_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0","mfa_csrf=; Path=/; Secure; SameSite=Strict; Max-Age=0"])}
  return out({ok:false,message:"We could not complete that step. Please try again."},404)
}

const HTML=String.raw`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Local Bank MFA</title><style>
body{margin:0;background:#eef4f8;color:#14283d;font:17px/1.65 Verdana,Arial,sans-serif;letter-spacing:.03em}.shell{max-width:580px;min-height:100vh;margin:auto;padding:22px;background:white}h1{font-size:1.6rem;line-height:1.3}.brand{font-weight:bold;color:#064a98}.step,.small{color:#526779;font-size:.9rem}.card,.hint{border:1px solid #c9d6e1;border-radius:10px;padding:16px;margin:16px 0}.hint{border-left:5px solid #075bc7;background:#f5faff}input,button{font:inherit;letter-spacing:inherit;box-sizing:border-box}input{width:100%;padding:13px;border:2px solid #8499ac;border-radius:8px}.code{text-align:center;font-size:1.4rem;font-weight:bold;letter-spacing:.2em}.primary,.secondary{width:100%;margin-top:16px;padding:14px;border-radius:8px;font-weight:bold}.primary{background:#075bc7;color:white;border:0}.secondary{color:#064d9e;background:#fff;border:2px solid #075bc7}.message{padding:12px;border-radius:8px;background:#e5f6ed;margin:14px 0}.error{background:#fff0ef;color:#a92319}.secret{font-family:monospace;word-break:break-all;background:#f4f7f9;padding:12px;border-radius:7px}.qr{display:block;width:min(100%,300px);margin:15px auto;image-rendering:pixelated}.logs{margin-top:30px;border-top:2px solid #c9d6e1}.logs pre{white-space:pre-wrap;background:#0e2436;color:#dff5ff;padding:12px;border-radius:8px;font:12px monospace}.hide{display:none}</style>
<body><main class="shell"><header><div class="brand">🏦 Local Bank</div><div id="step" class="step">Secure account setup</div></header><section id="app" aria-live="polite"></section><section class="logs"><h2>🧾 Logs</h2><p class="small">Simulation messages appear here and in the browser console.</p><pre id="logs">Ready.</pre></section></main><script>
(()=>{let csrf="",mode=false;const app=document.querySelector("#app"),logs=document.querySelector("#logs"),step=document.querySelector("#step");
const E=(t,a={},x="")=>{let e=document.createElement(t);Object.entries(a).forEach(([k,v])=>k.startsWith("on")?e.addEventListener(k.slice(2),v):e.setAttribute(k,v));e.textContent=x;return e}, log=x=>{console.log(x);logs.textContent+="\\n"+x}, msg=(x,b=false)=>E("div",{class:"message "+(b?"error":"")},x), hint=()=>E("p",{class:"hint"},"💡 Need help? Take your time. Retrying is safe and does not penalize you.");
const ck=n=>{let x=document.cookie.split("; ").find(x=>x.startsWith(n+"="));return x?decodeURIComponent(x.split("=").slice(1).join("=")):""};
async function api(p,m="GET",b){let r=await fetch(p,{method:m,credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:b?JSON.stringify(b):undefined}),d=await r.json();return d}
/* Task: standards-compliant QR Version 10-L: RS ECC, interleaving, mask scoring, format and version bits. */
function qrSvg(text){const N=57,exp=[],lg=[],A=new TextEncoder().encode(text);let z=1;for(let i=0;i<255;i++){exp[i]=z;lg[z]=i;z<<=1;if(z&256)z^=285}for(let i=255;i<512;i++)exp[i]=exp[i-255];const mul=(a,b)=>a&&b?exp[lg[a]+lg[b]]:0,bit=[];const put=(v,n)=>{for(let i=n-1;i>=0;i--)bit.push(v>>>i&1)};put(4,4);put(A.length,16);A.forEach(x=>put(x,8));while(bit.length<Math.min(2192,bit.length+4))bit.push(0);while(bit.length%8)bit.push(0);let dat=[];for(let i=0;i<bit.length;i+=8)dat.push(bit.slice(i,i+8).reduce((a,b)=>a*2+b));for(let i=0;dat.length<274;i++)dat.push(i%2?17:236);let g=[1];for(let i=0;i<18;i++){g.push(0);for(let j=g.length-1;j;j--)g[j]=g[j-1]^mul(g[j],exp[i]);g[0]=mul(g[0],exp[i])}let bs=[],o=0;[68,68,69,69].forEach(n=>{let d=dat.slice(o,o+=n),r=d.concat(Array(18).fill(0));for(let i=0;i<d.length;i++)if(r[i])for(let j=0;j<g.length;j++)r[i+j]^=mul(g[j],r[i]);bs.push([d,r.slice(-18)])});let stream=[];for(let i=0;i<69;i++)bs.forEach(b=>i<b[0].length&&stream.push(b[0][i]));for(let i=0;i<18;i++)bs.forEach(b=>stream.push(b[1][i]));let base=Array.from({length:N},()=>Array(N).fill(null)),S=(m,r,c,v)=>r>=0&&c>=0&&r<N&&c<N&&(m[r][c]=v),F=(m,r,c)=>{for(let y=-1;y<8;y++)for(let x=-1;x<8;x++)S(m,r+y,c+x,y>=0&&y<7&&x>=0&&x<7&&(y==0||y==6||x==0||x==6||(y>1&&y<5&&x>1&&x<5)))};F(base,0,0);F(base,0,50);F(base,50,0);for(let r of [6,28,50])for(let c of [6,28,50])if(base[r][c]===null)for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++)S(base,r+y,c+x,Math.max(Math.abs(x),Math.abs(y))!=1);for(let i=8;i<N-8;i++){if(base[6][i]===null)S(base,6,i,!(i&1));if(base[i][6]===null)S(base,i,6,!(i&1))}S(base,N-8,8,true);for(let i=0;i<9;i++){S(base,i,8,false);S(base,8,i,false)}for(let i=0;i<8;i++){S(base,8,N-1-i,false);S(base,N-1-i,8,false)}for(let i=0;i<18;i++){S(base,Math.floor(i/3),N-11+i%3,false);S(base,N-11+i%3,Math.floor(i/3),false)}
const fmt=(m,k)=>{let f=((1<<3)|k)<<10,q=f;while(q>=0x537)q^=0x537<<(31-Math.clz32(q)-10);f=(f|q)^0x5412;for(let i=0;i<6;i++)S(m,i,8,f>>i&1);S(m,7,8,f>>6&1);S(m,8,8,f>>7&1);S(m,8,7,f>>8&1);for(let i=9;i<15;i++)S(m,14-i,8,f>>i&1);for(let i=0;i<8;i++)S(m,8,N-1-i,f>>i&1);for(let i=8;i<15;i++)S(m,8,N-15+i,f>>i&1);let v=10<<12,q=v;while(q>=0x1f25)q^=0x1f25<<(31-Math.clz32(q)-12);v|=q;for(let i=0;i<18;i++){let b=v>>i&1;S(m,Math.floor(i/3),N-11+i%3,b);S(m,N-11+i%3,Math.floor(i/3),b)}};let best,bp=1e9;for(let k=0;k<8;k++){let m=base.map(r=>r.slice()),i=0,up=true;for(let c=N-1;c>0;c-=2){if(c==6)c--;for(let q=0;q<N;q++){let r=up?N-1-q:q;for(let x=0;x<2;x++)if(m[r][c-x]===null){let v=i<stream.length*8?(stream[i>>3]>>(7-(i++&7))&1):0,mask=[(r+c-x)%2==0,r%2==0,(c-x)%3==0,(r+c-x)%3==0,(Math.floor(r/2)+Math.floor((c-x)/3))%2==0,(r*(c-x))%2+(r*(c-x))%3==0,((r*(c-x))%2+(r*(c-x))%3)%2==0,((r+c-x)%2+(r*(c-x))%3)%2==0][k];m[r][c]=!!(v^mask)}}up=!up}fmt(m,k);let p=0;for(let r=0;r<N;r++)for(let c=0;c<N;c++){if(c&&m[r][c]==m[r][c-1])p++;if(r&&m[r][c]==m[r-1][c])p++}if(p<bp){bp=p;best=m}}let path="";best.forEach((r,y)=>r.forEach((v,x)=>v&&(path+="M"+x+" "+y+"h1v1h-1z")));let s=E("svg",{class:"qr",viewBox:"0 0 57 57",role:"img","aria-label":"Scannable authenticator setup QR code"});s.append(E("path",{d:path,fill:"#000"}));return s}
function signin(){app.replaceChildren(E("h1",{},"Sign in to start MFA setup"));let f=E("form"),e=E("input",{type:"email",placeholder:"marcus@example.com"}),p=E("input",{type:"password",placeholder:"BankPass!42"});f.append(E("p",{},"Email"),e,E("p",{},"Password"),p,E("button",{class:"primary",type:"submit"},"Sign in"));f.onsubmit=async x=>{x.preventDefault();let d=await api("/api/signin","POST",{email:e.value,password:p.value});if(!d.ok)return f.prepend(msg(d.message,true));csrf=d.csrf;mode=d.academicMode;identity()};app.append(f,hint())}
function identity(){app.replaceChildren(E("h1",{},"Verify it is you"),E("p",{},"📩 Send one short code."));let b=E("button",{class:"primary"},"Send identity code");b.onclick=async()=>{let d=await api("/api/identity/send","POST",{});if(d.simulationCode){console.log("ACADEMIC SIMULATION identity code:",d.simulationCode);log("Identity test code delivered to browser console.")}let f=E("form"),i=E("input",{class:"code",placeholder:"123456"});f.append(i,E("button",{class:"primary",type:"submit"},"Check code"));f.onsubmit=async e=>{e.preventDefault();let x=await api("/api/identity/verify","POST",{code:i.value});x.ok?setup():f.prepend(msg(x.message,true))};app.append(f)};app.append(b,hint())}
async function setup(){let d=await api("/api/authenticator/setup","POST",{});app.replaceChildren(E("h1",{},"Set up your authenticator"),E("p",{},"📱 Scan this QR code, or copy the setup key."),qrSvg(d.uri),E("div",{class:"secret"},d.secret));let b=E("button",{class:"primary"},"I added it to my app");b.onclick=async()=>{let x=await api("/api/authenticator/confirm","POST",{});if(x.simulationCode){console.log("ACADEMIC SIMULATION authenticator test code:",x.simulationCode);log("Authenticator test code delivered to browser console.")}confirm()};app.append(b,hint())}
function confirm(){app.replaceChildren(E("h1",{},"Check your authenticator"),E("p",{},"🔢 Enter the current 6-digit code. Take as long as you need."));let f=E("form"),i=E("input",{class:"code",placeholder:"123456"}),refresh=E("button",{class:"secondary",type:"button"},"Get a new test code");refresh.onclick=async()=>{let d=await api("/api/authenticator/refresh","POST",{});if(d.simulationCode){console.log("ACADEMIC SIMULATION refreshed authenticator code:",d.simulationCode);log("New current test code delivered to browser console. Retrying is safe.")}app.append(msg(d.message))};f.append(i,E("button",{class:"primary",type:"submit"},"Confirm authenticator"));f.onsubmit=async e=>{e.preventDefault();let d=await api("/api/authenticator/verify","POST",{code:i.value});d.ok?recovery():f.prepend(msg(d.message,true))};app.append(f,refresh,hint())}
async function recovery(){let d=await api("/api/recovery/create","POST",{}),ul=E("div",{class:"secret"},d.codes.join("\\n"));console.log("ACADEMIC SIMULATION recovery codes:",d.codes);log("Recovery codes delivered to browser console.");let b=E("button",{class:"primary"},"I saved my codes");b.onclick=async()=>{await api("/api/recovery/finish","POST",{});app.replaceChildren(E("h1",{},"MFA is ready"),msg("MFA is now on."),E("p",{},"✅ Your authenticator and recovery codes are set up."))};app.replaceChildren(E("h1",{},"Save recovery codes"),E("p",{},"🗝️ Keep these somewhere private."),ul,b,hint())}
(async()=>{csrf=ck("mfa_csrf");if(!csrf){csrf=crypto.getRandomValues(new Uint32Array(3)).join("");document.cookie="mfa_csrf="+csrf+"; Path=/; Secure; SameSite=Strict"}let d=await api("/api/me");d.ok&&d.stage==="confirm"?(csrf=d.csrf,confirm()):signin()})()})()</script></body></html>`;

Bun.serve({
  hostname:"localhost",port:3000,
  tls:{cert:Bun.file("certs/cert.pem"),key:Bun.file("certs/key.pem")},
  fetch:async r=>{try{const u=new URL(r.url);if(u.pathname==="/"&&r.method==="GET")return new Response(HTML,{headers:{...headers,"Content-Type":"text/html; charset=utf-8"}});if(u.pathname.startsWith("/api/"))return api(r,u.pathname);return out({ok:false,message:"Not found."},404)}catch{return out({ok:false,message:"We could not complete that step."},500)}}
});
