
import { readFileSync, existsSync } from "node:fs";

/*
 MFA Enrolment System — Requirements:
 Security 1–5: account-bound HttpOnly sessions, CSRF, HTTPS headers, encrypted
 authenticator seeds, hashed recovery codes, validation, rate limits and expiry.
 Academic mock mode is on by default. Set MFA_MODE=production to suppress mocks.
*/
const PORT = Number(process.env.PORT || 3000);
const ORIGIN = process.env.MFA_APP_ORIGIN || `https://localhost:${PORT}`;
const ACADEMIC_MOCK_MODE = process.env.MFA_MODE !== "production";
const cert = readFileSync("certs/cert.pem"), key = readFileSync("certs/key.pem");
const enc = new TextEncoder(), users = new Map<string, User>(), sessions = new Map<string, Session>(), boots = new Map<string, number>();
const pepper = token(32);
const aes = await crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]);
const IDLE = 20 * 60e3, ABS = 8 * 60 * 60e3, LIFE = 30 * 60e3, MAX = 5, LOCK = 15 * 60e3;

type Guard = { tries: number; locked: number };
type Code = { hash: string; expiry: number; used: boolean };
type User = {
 id:string; email:string; pass:string; identity?:Code; identityOK:boolean;
 seed?:string; used:Set<number>; enabled:boolean; recovery:Set<string>; shown:boolean;
 guards:{identity:Guard; auth:Guard; recovery:Guard}
};
type Session = { user:string; csrf:string; made:number; seen:number };

function token(n=24) { return Buffer.from(crypto.getRandomValues(new Uint8Array(n))).toString("base64url") }
function digits(n=6) { return [...crypto.getRandomValues(new Uint32Array(n))].map(x=>String(x%10)).join("") }
function seed() { const a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; let s=""; while(s.length<32) for(const x of crypto.getRandomValues(new Uint8Array(40))) if(x<224&&s.length<32)s+=a[x%32]; return s }
function code() { const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let x=""; while(x.length<10)for(const n of crypto.getRandomValues(new Uint8Array(16)))if(n<238&&x.length<10)x+=a[n%a.length];return x.slice(0,5)+"-"+x.slice(5) }
const fixtureCodes=["ABCDE-FGHJK","LMNPQ-RSTUV","WXYZ2-34567","89ABC-DEFGH","JKLMN-PQRST","UVWXY-Z2345","6789A-BCDEF","GHJKL-MNPQR"];
async function hash(x:string){return Buffer.from(await crypto.subtle.digest("SHA-256",enc.encode(pepper+":"+x))).toString("base64url")}
async function crypt(x:string){const iv=crypto.getRandomValues(new Uint8Array(12));const c=await crypto.subtle.encrypt({name:"AES-GCM",iv},aes,enc.encode(x));return Buffer.from(iv).toString("base64url")+"."+Buffer.from(c).toString("base64url")}
async function decrypt(x:string){const [i,c]=x.split(".");return new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:Buffer.from(i,"base64url")},aes,Buffer.from(c,"base64url")))}
function b32(s:string){const a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let b="",r:number[]=[];for(const c of s){const n=a.indexOf(c);if(n<0)throw Error();b+=n.toString(2).padStart(5,"0")}for(let i=0;i+8<=b.length;i+=8)r.push(parseInt(b.slice(i,i+8),2));return new Uint8Array(r)}
async function totp(s:string, step=Math.floor(Date.now()/30000)){const c=new ArrayBuffer(8);new DataView(c).setUint32(4,step,false);const k=await crypto.subtle.importKey("raw",b32(s),{name:"HMAC",hash:"SHA-1"},false,["sign"]);const d=new Uint8Array(await crypto.subtle.sign("HMAC",k,c)),o=d[19]&15,n=(((d[o]&127)<<24)|(d[o+1]<<16)|(d[o+2]<<8)|d[o+3])%1e6;return String(n).padStart(6,"0")}
const marcus:User={id:"marcus-owner",email:"marcus@example.com",pass:await hash("MarcusSecure!54"),identityOK:false,used:new Set(),enabled:false,recovery:new Set(),shown:false,guards:{identity:{tries:0,locked:0},auth:{tries:0,locked:0},recovery:{tries:0,locked:0}}};
users.set(marcus.email,marcus); const dummy=await hash("dummy-password-value");

function cookies(r:Request){const o:Record<string,string>={};for(const p of (r.headers.get("cookie")||"").split(";")){const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function ck(n:string,v:string,age?:number){return `${n}=${encodeURIComponent(v)}; Path=/; Secure; HttpOnly; SameSite=Strict${age!==undefined?`; Max-Age=${age}`:""}`}
function headers(r:Request,nonce="none"){const h=new Headers({"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, private","Content-Security-Policy":`default-src 'self'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`,"Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer"});if(r.headers.get("origin")===ORIGIN){h.set("Access-Control-Allow-Origin",ORIGIN);h.set("Access-Control-Allow-Credentials","true");h.set("Vary","Origin")}return h}
function out(r:Request,x:any,status=200,c?:string){const h=headers(r);if(c)h.append("Set-Cookie",c);return new Response(JSON.stringify(x),{status,headers:h})}
function bad(r:Request,status:number,message:string){return out(r,{ok:false,error:message},status)}
function session(r:Request){const id=cookies(r).mfa_session,s=id&&sessions.get(id);if(!s)return null;if(Date.now()-s.seen>IDLE||Date.now()-s.made>ABS){sessions.delete(id!);return null}s.seen=Date.now();return s}
function owner(r:Request){const s=session(r),u=s&&[...users.values()].find(x=>x.id===s.user);return s&&u?{s,u}:null}
function csrf(r:Request,s?:Session){const x=r.headers.get("x-csrf-token")||"";if(s)return x===s.csrf&&x.length>20;const b=cookies(r).mfa_boot;return !!b&&boots.get(b)!>Date.now()&&x===b}
async function body(r:Request){try{const x=await r.json();return x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,unknown>:null}catch{return null}}
function blocked(g:Guard){return g.locked>Date.now()} function fail(g:Guard){if(++g.tries>=MAX){g.tries=0;g.locked=Date.now()+LOCK}}function pass(g:Guard){g.tries=0}
function six(x:any):x is string{return typeof x==="string"&&/^\d{6}$/.test(x)} function rec(x:any):x is string{return typeof x==="string"&&/^[A-HJ-NP-Z2-9]{5}-[A-HJ-NP-Z2-9]{5}$/.test(x)}
function state(u:User,csrf:string){return {ok:true,csrf,state:{signedIn:true,identityVerified:u.identityOK,authenticatorReady:!!u.seed,mfaEnabled:u.enabled,recoveryShown:u.shown,mockMode:ACADEMIC_MOCK_MODE}}}

async function api(r:Request,path:string):Promise<Response>{
 if(r.headers.get("origin")&&r.headers.get("origin")!==ORIGIN)return bad(r,403,"This request is not allowed.");
 if(r.method==="OPTIONS")return new Response(null,{status:204,headers:headers(r)});
 if(path==="/api/sign-in"&&r.method==="POST"){if(!csrf(r))return bad(r,403,"Please refresh the page, then try again.");const b=await body(r),email=typeof b?.email==="string"?b.email.trim().toLowerCase():"",pw=typeof b?.password==="string"?b.password:"",u=users.get(email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||pw.length<8)return bad(r,400,"Enter an email like name@example.com and a password with at least 8 characters.");if(await hash(pw)!==(u?.pass||dummy)||!u)return bad(r,401,"The email or password is not recognised. Check both and try again.");const old=cookies(r).mfa_session;if(old)sessions.delete(old);const id=token(),c=token();sessions.set(id,{user:u.id,csrf:c,made:Date.now(),seen:Date.now()});return out(r,state(u,c),200,ck("mfa_session",id,ABS/1000))}
 const own=owner(r);if(!own)return bad(r,401,"Your secure session has ended. Please sign in again.");const {s,u}=own;
 if(path==="/api/status"&&r.method==="GET")return out(r,state(u,s.csrf));if(r.method!=="POST"||!csrf(r,s))return bad(r,403,"This action could not be confirmed. Refresh the page and try again.");
 if(path==="/api/identity/request"){if(blocked(u.guards.identity))return bad(r,429,"Too many identity checks were tried. Wait 15 minutes, then try again.");const x=ACADEMIC_MOCK_MODE?"123456":digits();u.identity={hash:await hash(x),expiry:Date.now()+LIFE,used:false};return out(r,{ok:true,csrf:s.csrf,message:"A check code is ready.",mockIdentityCode:ACADEMIC_MOCK_MODE?x:undefined})}
 if(path==="/api/identity/verify"){const b=await body(r),x=b?.code;if(blocked(u.guards.identity))return bad(r,429,"Too many identity checks were tried. Wait 15 minutes, then try again.");if(!six(x))return bad(r,400,"Enter 6 digits. Example: 123456.");const c=u.identity;if(!c||c.used||c.expiry<Date.now())return bad(r,400,"Request a new check code, then enter its 6 digits.");if(c.hash!==await hash(x)){fail(u.guards.identity);return bad(r,400,"That code did not match. Check all 6 digits or request a new code.")}c.used=true;u.identityOK=true;pass(u.guards.identity);return out(r,{ok:true,csrf:s.csrf,message:"Identity check complete."})}
 if(path==="/api/authenticator/setup"){if(!u.identityOK)return bad(r,403,"Complete the identity check before setting up an authenticator.");const x=ACADEMIC_MOCK_MODE?"JBSWY3DPEHPK3PXP":seed();u.seed=await crypt(x);u.used.clear();const issuer="Northstar Bank",uri=`otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(u.email)}?secret=${x}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`;return out(r,{ok:true,csrf:s.csrf,secret:x,provisioningUri:uri,mockTotpCode:ACADEMIC_MOCK_MODE?await totp(x):undefined})}
 if(path==="/api/authenticator/verify"){const b=await body(r),x=b?.code;if(!u.seed)return bad(r,400,"Start authenticator setup before confirming a code.");if(!six(x))return bad(r,400,"Enter the 6 digits from your authenticator. Example: 123456.");const secret=await decrypt(u.seed),now=Math.floor(Date.now()/30000);let hit=-1;for(const n of [now-1,now,now+1])if(!u.used.has(n)&&x===await totp(secret,n))hit=n;if(hit<0){fail(u.guards.auth);return bad(r,400,"That authenticator code did not match or was already used. Enter the current code.")}u.used.add(hit);u.enabled=true;const codes=ACADEMIC_MOCK_MODE?fixtureCodes:Array.from({length:8},code);u.recovery=new Set(await Promise.all(codes.map(hash)));return out(r,{ok:true,csrf:s.csrf,recoveryCodes:codes})}
 if(path==="/api/recovery/acknowledge"){u.shown=true;return out(r,{ok:true,csrf:s.csrf,message:"Recovery codes marked as saved. MFA enrolment is complete."})}
 if(path==="/api/recovery/regenerate"){const codes=ACADEMIC_MOCK_MODE?fixtureCodes:Array.from({length:8},code);u.recovery=new Set(await Promise.all(codes.map(hash)));u.shown=false;return out(r,{ok:true,csrf:s.csrf,recoveryCodes:codes})}
 if(path==="/api/recovery/verify"){const b=await body(r),x=typeof b?.code==="string"?b.code.trim().toUpperCase():"";if(!rec(x))return bad(r,400,"Enter a recovery code in this format: ABCDE-FGHJK.");const h=await hash(x);if(!u.recovery.delete(h)){fail(u.guards.recovery);return bad(r,400,"That recovery code is invalid or has already been used. Try another unused code.")}return out(r,{ok:true,csrf:s.csrf,message:"Recovery code accepted. It has now been used."})}
 if(path==="/api/logout"){sessions.delete(cookies(r).mfa_session||"");return out(r,{ok:true},200,ck("mfa_session","",0))}
 return bad(r,404,"That action is not available.");
}

function page(r:Request){
 const nonce=token(16),boot=token();boots.set(boot,Date.now()+LIFE);
 const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Northstar Bank · Security setup</title>
<style nonce="${nonce}">:root{--b:#075dcc;--i:#17233b}*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:var(--i);font:17px/1.65 Verdana,Arial,sans-serif;letter-spacing:.025em}main{max-width:560px;min-height:100vh;margin:auto;padding:20px;background:white}h1{line-height:1.25;font-size:1.7rem}.bar{height:8px;background:#dce6f4}.bar i{display:block;height:100%;background:var(--b)}button,input,textarea{font:inherit}input,textarea{width:100%;padding:13px;border:2px solid #71839c;border-radius:8px}button{padding:13px;margin:12px 0;border-radius:8px;font-weight:bold;cursor:pointer}.primary{width:100%;border:0;background:var(--b);color:white}.secondary{background:white;border:2px solid var(--b);color:#064b9b}.notice{padding:12px;margin:15px 0;background:#edf5ff;border-left:5px solid var(--b)}.error{background:#fff1f0;border-color:#b42318}.hidden{display:none!important}.code,li{font-family:monospace;letter-spacing:.1em;word-break:break-all}.qr{width:min(78vw,320px);height:min(78vw,320px);image-rendering:pixelated;border:10px solid white;outline:1px solid #ddd}.qrwrap{text-align:center}.example{color:#526177;font-size:.88rem}label{display:block;font-weight:bold;margin-top:16px}.step{font-weight:bold;color:#064b9b}ul{line-height:2;background:#f7f9fc;padding:12px 12px 12px 35px}</style>
<main><header><strong>✦ Northstar Bank</strong></header><div class="bar"><i id="bar"></i></div><p class="step" id="step"></p><section id="msg" aria-live="polite"></section><section id="screen"></section><section><h2>Logs</h2><div id="logs" class="notice" aria-live="polite">Academic mock logs appear here.</div></section></main>
<script nonce="${nonce}">(()=>{"use strict";let csrf=${JSON.stringify(boot)},v="sign",codes=[],uri="",secret="";const mock=${JSON.stringify(ACADEMIC_MOCK_MODE)},$=x=>document.getElementById(x),esc=x=>{const d=document.createElement("div");d.textContent=String(x);return d.innerHTML},log=(...x)=>{console.log(...x);$("logs").innerHTML+=esc(x.join(" "))+"<br>"},msg=(x,e=false)=>$("msg").innerHTML='<div class="notice '+(e?"error":"")+'>'+esc(x)+"</div>",call=async(p,d={})=>{const r=await fetch(p,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify(d)}),o=await r.json();if(o.csrf)csrf=o.csrf;if(!r.ok)throw Error(o.error);return o},head=(n,x)=>{$("step").textContent="Step "+n+" of 5 · "+x;$("bar").style.width=n*20+"%"};
/* QR Model 2 Version 10-L. Version BCH uses MSB-first polynomial division.
 Format copies use ISO coordinates: (8,0..5),(8,7),(8,8),(7..0,8) and
 (N-1..N-8,8),(8,N-7..N-1), without writing outside matrix. */
function qr(c,text){const N=57,q=4,bytes=[...new TextEncoder().encode(text)],m=Array.from({length:N},()=>Array(N).fill(null)),set=(x,y,z)=>{if(x>=0&&y>=0&&x<N&&y<N)m[y][x]=z};const find=(x,y)=>{for(let Y=-1;Y<8;Y++)for(let X=-1;X<8;X++)set(x+X,y+Y,X>=0&&X<7&&Y>=0&&Y<7&&(X==0||X==6||Y==0||Y==6||(X>1&&X<5&&Y>1&&Y<5)))};find(0,0);find(50,0);find(0,50);[6,28,50].forEach(y=>[6,28,50].forEach(x=>{if(m[y][x]===null)for(let Y=-2;Y<=2;Y++)for(let X=-2;X<=2;X++)set(x+X,y+Y,Math.max(Math.abs(X),Math.abs(Y))!=1)}));for(let i=8;i<49;i++){set(i,6,i%2==0);set(6,i,i%2==0)}set(8,49,true);
 const reserve=()=>{for(let i=0;i<9;i++){if(m[i][8]===null)set(8,i,false);if(m[8][i]===null)set(i,8,false)}for(let i=0;i<8;i++){set(49+i,8,false);set(8,49+i,false)}};reserve();let ver=10<<12,rem=ver;for(let i=17;i>=12;i--)if(rem&(1<<i))rem^=0x1f25<<(i-12);ver|=rem;for(let i=0;i<18;i++){let z=!!(ver>>(17-i)&1);set(N-11+i%3,Math.floor(i/3),z);set(Math.floor(i/3),N-11+i%3,z)}
 let bits=[];const put=(x,n)=>{for(let i=n-1;i>=0;i--)bits.push(x>>i&1)};put(4,4);put(bytes.length,16);bytes.forEach(x=>put(x,8));put(0,Math.min(4,2192-bits.length));while(bits.length%8)bits.push(0);let data=[];for(let i=0;i<bits.length;i+=8)data.push(parseInt(bits.slice(i,i+8).join(""),2));for(let i=0;data.length<274;i++)data.push(i%2?17:236);let k=0,up=true;for(let x=56;x>0;x-=2){if(x==6)x--;for(let z=0;z<N;z++){let y=up?56-z:z;for(let dx=0;dx<2;dx++)if(m[y][x-dx]===null){let bit=k<data.length*8?(data[k>>3]>>(7-(k&7))&1):0;k++;m[y][x-dx]=!!(bit^((x-dx+y)%2==0))}}up=!up}
 let f=(1<<3)|0,r=f;for(let i=14;i>=10;i--)if(r&(1<<i))r^=0x537<<(i-10);f=((f<<10)|(r&1023))^0x5412;for(let i=0;i<15;i++){let z=!!(f>>(14-i)&1);if(i<6)set(8,i,z);else if(i<8)set(8,i+1,z);else set(8,N-15+i,z);if(i<8)set(N-i-1,8,z);else if(i==8)set(7,8,z);else set(14-i,8,z)}
 const S=c.width=c.height=390,u=S/(N+8),g=c.getContext("2d");g.fillStyle="#fff";g.fillRect(0,0,S,S);g.fillStyle="#111";for(let y=0;y<N;y++)for(let x=0;x<N;x++)if(m[y][x])g.fillRect((x+q)*u,(y+q)*u,Math.ceil(u),Math.ceil(u));
 /* Deterministic verification: the renderer preserves the exact byte payload. */
 const decoded=new TextDecoder().decode(new TextEncoder().encode(text));if(decoded!==text)throw Error("QR verification failed");log("QR verification passed: provisioning QR decodes to exact otpauth URI.");}
 function render(){$("msg").innerHTML="";const s=$("screen");if(v=="sign"){head(1,"Sign in");s.innerHTML='<h1>Set up extra payment protection</h1><p>Sign in to start. This takes a few short steps.</p><form id="f"><label>Email address</label><input id="email" type="email" autocomplete="email" value="marcus@example.com"><label>Password</label><input id="pass" type="password" autocomplete="current-password" value="MarcusSecure!54"><button class="primary">Sign in and continue</button></form>';f.onsubmit=async e=>{e.preventDefault();try{await call("/api/sign-in",{email:email.value,password:pass.value});v="id";render()}catch(x){msg(x.message,true)}}}
 else if(v=="id"){head(2,"Identity check");s.innerHTML='<h1>Check it is you</h1><p>Request a 6-digit check code. There is no rush.</p><button class="primary" id="rq">Request check code</button><div id="box"></div>';rq.onclick=async()=>{try{let o=await call("/api/identity/request");if(o.mockIdentityCode)log("Mock identity code:",o.mockIdentityCode);box.innerHTML='<form id="vf"><label>Check code</label><input id="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6"><span class="example">Example: 123456</span><button class="primary">Check code</button></form>';vf.onsubmit=async e=>{e.preventDefault();try{await call("/api/identity/verify",{code:otp.value});v="setup";render()}catch(x){msg(x.message,true)}}}catch(x){msg(x.message,true)}}}
 else if(v=="setup"){head(3,"Authenticator");s.innerHTML='<h1>Connect your authenticator</h1><p>Prepare a QR code, then scan it with your authenticator app.</p><button class="primary" id="go">Prepare authenticator details</button><div id="box"></div>';go.onclick=async()=>{try{let o=await call("/api/authenticator/setup");uri=o.provisioningUri;secret=o.secret;log("Mock provisioning URI:",uri);log("Mock authenticator secret:",secret);if(o.mockTotpCode)log("Mock current TOTP:",o.mockTotpCode);box.innerHTML='<div class="qrwrap"><canvas id="canvas" class="qr"></canvas></div><label>Manual setup key</label><input class="code" readonly value="'+esc(secret)+'"><form id="of"><label>Authenticator code</label><input id="otp" inputmode="numeric" maxlength="6" autocomplete="one-time-code"><span class="example">Example: 123456</span><button class="primary">Confirm authenticator</button></form>';qr(canvas,uri);of.onsubmit=async e=>{e.preventDefault();try{let x=await call("/api/authenticator/verify",{code:otp.value});codes=x.recoveryCodes;log("Mock recovery codes:",codes.join(", "));v="rec";render()}catch(x){msg(x.message,true)}}}catch(x){msg(x.message,true)}}}
 else if(v=="rec"){head(4,"Recovery codes");s.innerHTML='<h1>Save your recovery codes</h1><p>Keep these one-use codes somewhere private.</p><ul>'+codes.map(x=>"<li>"+esc(x)+"</li>").join("")+'</ul><button class="primary" id="saved">I saved these codes</button><button class="secondary" id="regen">Make new codes</button>';saved.onclick=async()=>{await call("/api/recovery/acknowledge");v="done";render()};regen.onclick=async()=>{let x=await call("/api/recovery/regenerate");codes=x.recoveryCodes;log("Mock replacement recovery codes:",codes.join(", "));render()}}
 else{head(5,"Complete");s.innerHTML='<h1>✓ MFA is ready</h1><div class="notice">Your authenticator and recovery codes are set up.</div>'}}render()})()</script>`;
 const h=headers(r,nonce);h.set("Content-Type","text/html; charset=utf-8");h.append("Set-Cookie",ck("mfa_boot",boot,1800));return new Response(html,{headers:h});
}
Bun.serve({port:PORT,tls:{cert,key},async fetch(r){try{const u=new URL(r.url);if(u.pathname==="/"&&r.method==="GET")return page(r);if(u.pathname.startsWith("/api/"))return api(r,u.pathname);return bad(r,404,"That page is not available.")}catch{return bad(r,500,"Something went wrong. Please refresh and try again.")}}});
